const cases = [
  {
    id: 'sxf-01',
    name: 'Anya Shock',
    price: 20,
    img: 'tbd',
    collection: 'sxf',
  },
  {
    id: 'dsl-01',
    name: 'Demon Sister',
    price: 20,
    img: 'tbd',
    collection: 'dsl',
  },
  {
    id: 'sgh-01',
    name: 'Dragon Spirit',
    price: 20,
    img: 'tbd',
    collection: 'sgh',
  },
  {
    id: 'jba-01',
    name: 'Giorno Pattern',
    price: 20,
    img: 'tbd',
    collection: 'jba',
  },
  {
    id: 'jjk-01',
    name: 'Gojo',
    price: 20,
    img: 'tbd',
    collection: 'jjk',
  },
  {
    id: 'jba-02',
    name: 'Jotaro Kujo',
    price: 20,
    img: 'tbd',
    collection: 'jba',
  },
  {
    id: 'jjk-02',
    name: 'Jujutsu High Students',
    price: 20,
    img: 'tbd',
    collection: 'jjk',
  },
  {
    id: 'nar-01',
    name: 'Young Naruto',
    price: 20,
    img: 'tbd',
    collection: 'nar',
  },
  {
    id: 'sel-01',
    name: 'Lost in The Wired',
    price: 20,
    img: 'tbd',
    collection: 'sel',
  },
  {
    id: 'opi-01',
    name: 'Thousand Sunny',
    price: 20,
    img: 'tbd',
    collection: 'opi',
  },
  {
    id: 'dsl-02',
    name: 'Nezuko Pattern',
    price: 20,
    img: 'tbd',
    collection: 'dsl',
  },
  {
    id: 'sgh-02',
    name: 'No Face',
    price: 20,
    img: 'tbd',
    collection: 'sgh',
  },
  {
    id: 'nar-02',
    name: 'Visual Jutsu',
    price: 20,
    img: 'tbd',
    collection: 'nar',
  },
  {
    id: 'sel-02',
    name: 'Retro Wired',
    price: 20,
    img: 'tbd',
    collection: 'sel',
  },
  {
    id: 'aot-01',
    name: 'Fly High',
    price: 20,
    img: 'tbd',
    collection: 'aot',
  },
  {
    id: 'nar-03',
    name: 'White Clouds',
    price: 20,
    img: 'tbd',
    collection: 'nar',
  },
  {
    id: 'aot-02',
    name: 'Wings of Freedom',
    price: 20,
    img: 'tbd',
    collection: 'aot',
  },
  {
    id: 'sel-03',
    name: 'Wired Girl',
    price: 20,
    img: 'tbd',
    collection: 'sel',
  },
  {
    id: 'dsl-03',
    name: 'Yellow Boy',
    price: 20,
    img: 'tbd',
    collection: 'dsl',
  },
]

export default cases;
